### ISSUE TITLE
youdao-dict运行报错

### ISSUE THREAD

**Issue by y-usuzumi** [gentoo-zh/overlay#385]
`Traceback (most recent call last):
  File "/usr/bin/youdao-dict", line 27, in <module>
    from dae.daeclient import DAEClient
  File "/usr/share/youdao-dict/dae/daeclient.py", line 36, in <module>
    from dae.window import Window
  File "/usr/share/youdao-dict/dae/window.py", line 29, in <module>
    from dae.webview import WebView
  File "/usr/share/youdao-dict/dae/webview.py", line 27, in <module>
    from dae.webpage import WebPage
  File "/usr/share/youdao-dict/dae/webpage.py", line 27, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage, QWebInspector
ImportError: No module named 'PyQt5.QtWebKitWidgets'`

是否应该在ebuild中对PyQt5加上webkit的use flag？

**Comment by biergaizi** [comment]
应该。
